# Site settings
title: Shane Lee Blog
email: 
description: ""
baseurl: ""
url: "http://shanelee.github.io"
github_username:  shanelee

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
